apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-night-service
  labels:
    app: good-night-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-night-service
  template:
    metadata:
      labels:
        app: good-night-service
    spec:
      containers:
      - name: good-night-service
        image: good-night-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1002
---
apiVersion: v1
kind: Service
metadata:
  name: good-night-service
spec:
  selector:
    app: good-night-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1002
