apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-evening-service
  labels:
    app: good-evening-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-evening-service
  template:
    metadata:
      labels:
        app: good-evening-service
    spec:
      containers:
      - name: good-evening-service
        image: good-evening-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1001
---
apiVersion: v1
kind: Service
metadata:
  name: good-evening-service
spec:
  selector:
    app: good-evening-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1001
